---
- name: Install Pyenv
  homebrew: name={{ item }} state=present
  with_items:
    - pyenv
    - ccache

- name: Install pyenv plugins
  git: repo={{ item.repo }} dest={{ item.dest }}
  with_items:
    - { repo: 'https://github.com/yyuu/pyenv-ccache.git', dest: '~/.pyenv/plugins/pyenv-ccache' }
    - { repo: 'https://github.com/yyuu/pyenv-doctor.git', dest: '~/.pyenv/plugins/pyenv-doctor' }
    - { repo: 'https://github.com/yyuu/pyenv-pip-migrate.git', dest: '~/.pyenv/plugins/pyenv-pip-migrate' }
    - { repo: 'https://github.com/yyuu/pyenv-update.git', dest: '~/.pyenv/plugins/pyenv-update' }
    - { repo: 'https://github.com/yyuu/pyenv-virtualenv.git', dest: '~/.pyenv/plugins/pyenv-virtualenv' }
    - { repo: 'https://github.com/yyuu/pyenv-virtualenvwrapper.git', dest: '~/.pyenv/plugins/pyenv-virtualenvwrapper' }
    - { repo: 'https://github.com/yyuu/pyenv-which-ext.git', dest: '~/.pyenv/plugins/pyenv-which-ext' }

- name: Update Pyenv
  command: pyenv update

- name: Install Python Versions
  command: creates=~/.pyenv/versions/{{ item }} pyenv install {{ item }}
  with_items:
    - 2.7.11
    - 3.5.2

- name: Set Default Pyenv
  command: pyenv global 2.7.11 3.5.2

- name: Install Global Python Requirements
  environment:
    PIP_REQUIRE_VIRTUALENV: false
  pip: executable={{ ansible_env.HOME }}/.pyenv/shims/pip name={{ item }}
  with_items:
    - virtualenvwrapper
