---
- name: Install Pyenv
  homebrew:
    name: ['pyenv', 'ccache']
    state: present

- name: Install pyenv plugins
  git: repo={{ item.repo }} dest={{ item.dest }}
  with_items:
    - { repo: 'https://github.com/yyuu/pyenv-ccache.git', dest: '~/.pyenv/plugins/pyenv-ccache' }
    - { repo: 'https://github.com/yyuu/pyenv-doctor.git', dest: '~/.pyenv/plugins/pyenv-doctor' }
    - { repo: 'https://github.com/yyuu/pyenv-pip-migrate.git', dest: '~/.pyenv/plugins/pyenv-pip-migrate' }
    - { repo: 'https://github.com/yyuu/pyenv-update.git', dest: '~/.pyenv/plugins/pyenv-update' }
    - { repo: 'https://github.com/yyuu/pyenv-virtualenv.git', dest: '~/.pyenv/plugins/pyenv-virtualenv' }
    - { repo: 'https://github.com/yyuu/pyenv-virtualenvwrapper.git', dest: '~/.pyenv/plugins/pyenv-virtualenvwrapper' }
    - { repo: 'https://github.com/yyuu/pyenv-which-ext.git', dest: '~/.pyenv/plugins/pyenv-which-ext' }

- name: Update Pyenv
  command: pyenv update

- name: Install Python Versions
  shell: creates=~/.pyenv/versions/{{ item }} CPPFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install {{ item }}
  with_items:
    - 3.13
  environment:
    LDFLAGS: -L/opt/homebrew/opt/zlib/lib
    CPPFLAGS: -I/opt/homebrew/opt/zlib/include

- name: Set Default Pyenv
  command: pyenv global 3.13

- name: Install Global Python Requirements
  environment:
    PIP_REQUIRE_VIRTUALENV: false
  pip:
    executable: "{{ ansible_env.HOME }}/.pyenv/shims/pip"
    name: ['virtualenvwrapper', 'awscli']

- name: uv install latest Pythons
  command: >
    uv python install
    3.8
    3.9
    3.10
    3.11
    3.12
    3.13
  register: uv_python_install
  changed_when: "'All requested versions already installed' not in uv_python_install.stderr"
  tags:
  - uv

- name: uv prune cache
  command: uv cache prune
  register: uv_prune
  changed_when: "'Removed' in uv_prune.stderr"
  tags:
  - uv
