---

# TODO: This task isn't working because become isn't working for some reason
# - name: Set standby delay to 24 hours (default is 1 hour)
#   tags: macos
#   become: yes
#   command: "pmset -a standbydelay 86400"

##############################
# General UI/UX                                                               #
##############################

- name: Disable the "Are you sure you want to open this application?" dialog
  tags: macos
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: int
    value: "0"

- name: Don’t display the annoying prompt when quitting iTerm
  tags: macos
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PromptOnQuit
    type: int
    value: "0"

- name: Mouse right click
  tags: macos
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: "1"

- name: Keyboard Initial Key Repeat
  tags: macos
  osx_defaults:
    key: KeyRepeat
    type: int
    value: 2

- name: Keyboard Key Repeat
  tags: macos
  osx_defaults:
    key: KeyRepeat
    type: int
    value: 2


##############################
# Finder
##############################

- name: Show all filename extensions
  tags: macos
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: boolean
    value: "true"

- name: Allow text selection in Quick Look
  tags: macos
  osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: boolean
    value: "true"

- name: Disable the warning when changing a file extension
  tags: macos
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: boolean
    value: "false"

- name: Empty Trash securely by default
  tags: macos
  osx_defaults:
    domain: com.apple.finder
    key: EmptyTrashSecurely
    type: integer
    value: "0"

- name: Show the ~/Library folder
  tags: macos
  command: "chflags nohidden ~/Library"


##############################
# Dock & hot corners
##############################

- name: Always show the Dock
  tags: macos
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: boolean
    value: "true"

- name: Trun on magnification
  tags: macos
  osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: boolean
    value: "true"

- name: Icon small size
  tags: macos
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 32.0

- name: Icon large size
  tags: macos
  osx_defaults:
    domain: com.apple.dock
    key: largesize
    type: float
    value: 64.0

- name: Top left screen corner (Disable Screen Saver)
  tags: macos
  osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: "6"

- name: Top Right screen corner (Mission Control)
  tags: macos
  osx_defaults:
    domain: com.apple.dock
    key: wvous-tr-corner
    type: int
    value: "2"

- name: Bottom left screen corner (Start Screen Saver)
  tags: macos
  osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: "5"

- name: Bottom right screen corner (Desktop)
  tags: macos
  osx_defaults:
    domain: com.apple.dock
    key: wvous-br-corner
    type: int
    value: "4"

##############################
# Misc
##############################

- name: Avoid creating .DS_Store files on network volumes
  tags: macos
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: boolean
    value: "true"
