# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# Theme repository: https://github.com/denysdovhan/spaceship-prompt
export ZSH_THEME="spaceship"
export SPACESHIP_PACKAGE_SHOW=false
export SPACESHIP_NODE_SHOW=false

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want disable red dots displayed while waiting for completion
# DISABLE_COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(
  aws
  brew
  docker
  docker-compose
  fabric
  git
  git-extras
  heroku
  npm
  pip
  vagrant
)

# Customize to your needs...
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/local/sbin:/usr/local/scripts:/usr/local/share/npm/bin:/usr/local/texbin:$PATH"

eval "$(brew shellenv)"
# This makes it so ZSH will use the default Homebrew directory for completions scripts
fpath=($HOMEBREW_PREFIX/share/zsh/site-functions $fpath)

source $ZSH/oh-my-zsh.sh

# Set default editor
export EDITOR='charm'

# LOAD Virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
export PIP_REQUIRE_VIRTUALENV=true

# Aliases
alias e=$EDITOR
alias duf='du -sk * | sort -n | perl -ne '\''($s,$f)=split(m{\t});for (qw(K M G)) {if($s<1024) {printf("%.1f",$s);print "$_\t$f"; last};$s=$s/1024}'\'

# Print Column Alias
alias c1="awk '{print \$1}'"
alias c2="awk '{print \$2}'"
alias c3="awk '{print \$3}'"
alias c4="awk '{print \$4}'"
alias c5="awk '{print \$5}'"
alias c6="awk '{print \$6}'"
alias c7="awk '{print \$7}'"
alias c8="awk '{print \$8}'"
alias c9="awk '{print \$9}'"

# Git Aliases
alias gh=github
alias gx=gitx
alias gd='git diff'
alias gdl='git log --pretty=oneline --abbrev-commit --since="6am" | perl -wpe "s/^([^\s]+)/-/g" | tail -r'
alias grb='git rebase --rebase-merges=rebase-cousins'
# Git Stash Working - only stash unstaged changes
alias gsw="git commit -m 'Save index' && git stash push -u -q && git reset --soft HEAD^"

# Python Aliases
alias wn=workon
alias wnv='workon ww_videos'
alias rmpyc='find . -name "*.pyc" -delete'

# run this if iterm2 is slow
alias itermspeed="sudo rm /private/var/log/asl/*.asl"

# Docker Clean Containers - Removes all stopped containers
alias dcc='docker rm $(docker ps -a -q)'

# Docker Clean Images - Remove the <none> images
alias dci='docker rmi $(docker images -a | grep "^<none>" | awk '\''{if (NR!=1) {print $3}}'\'')'

# Docker kill all running containers
alias dka='docker kill $(docker ps | awk '\''{if (NR!=1) {print $1}}'\'')'

# Run docker compose process with --rm
alias dcr='docker compose run'
alias dcrr='docker compose run --rm'
alias dcdn='docker compose down -t 0'

# Django Aliases via Docker
alias d='dcrr web ./manage.py'
alias dt='d test'
alias dtf='dt --failfast'
alias dmm='d makemigrations'
alias dm='d migrate'
alias ds='d shell'

# aws-vault
alias av=aws-vault
alias ava='aws-vault add'
alias avlt='aws-vault list'
alias avrt='aws-vault rotate'
alias ave='aws-vault exec'
alias avrm='aws-vault remove'
alias avl='aws-vault login'

# SETUP Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
# For some reason virtualenvwrapper_lazy doesn't run if we don't do pyenv init twice
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
pyenv virtualenvwrapper_lazy

# SSH, This makes it so you don't have to type your ssh private key passphrase after a reboot
ssh-add -K ~/.ssh/id_rsa &> /dev/null

# DOCKER SETTINGS
export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_BUILDKIT=1

# Initialize direnv
eval "$(direnv hook zsh)"

# TERRAFORM Alias Function
function tf {
  local tf_args=("${@:1}")
  aws-vault exec admin -- chamber exec terraform -- terraform "${tf_args[@]}"
}

# Ruby
export PATH="$HOMEBREW_PREFIX/opt/ruby/bin:$HOMEBREW_PREFIX/lib/ruby/gems/3.1.0/bin:$PATH"

# AppPack
alias ap=apppack
