---

- name: Install Homebrew Formulas
  tags: brew
  homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
    upgrade_all: yes
  loop: "{{ homebrew_packages }}"

- name: Run brew tap for packages
  tags: brew
  command: brew tap "{{ item }}"
  loop: "{{ homebrew_taps }}"
  changed_when: false
  become: false

- name: Install Homebrew Cask Packages
  tags: brew
  homebrew_cask:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
    upgrade_all: yes
  loop: "{{ homebrew_cask_packages }}"
