---

- name: Install Homebrew Formulas
  homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
    upgrade_all: yes
  with_items:
    - chamber
    - direnv
    - git
    - git-extras
    - just
    - node
    - pyenv
    - zsh
    - zlib

- name: Run brew tap for packages
  command: brew tap "{{ item }}"
  loop: "{{ homebrew_taps }}"
  changed_when: false
  become: false

- name: Install homebrew cask packages
  command: brew install {{ homebrew_cask_packages|join(" ") }}
