---

- name: Install Homebrew Formulas
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
    upgrade_all: yes
  with_items:
    - chamber
    - direnv
    - git
    - git-extras
    - node
    - pyenv
    - zsh
    - zlib
