---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Add Homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/cask
    - homebrew/cask-versions

- name: Install Homebrew Formulas
  homebrew:
    name: ['ccache', 'direnv', 'git', 'git-extras', 'mysql', 'nginx', 'node',
      'openconnect', 'postgresql', 'pyenv', 'redis', 'z', 'zsh']
    state: latest

- name: Install Casks
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - amazon-music
    - aws-vault
    - aerial
    - atom
    - bartender
    - dropbox
    - firefox
    - fork
    - goofy
    - google-chrome
    - google-drive-file-stream
    - iterm2
    - java
    - pgadmin4
    - pycharm
    - sequel-pro
    - slack
    - sourcetree
    - spectacle
    - spotify
    - vagrant
    - zoomus
