---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Add Homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/cask
    - homebrew/cask-versions

- name: Install Homebrew Formulas
  homebrew:
    name: ['ccache', 'chamber', 'direnv', 'git', 'git-extras', 'mysql', 'nginx',
      'node', 'openconnect', 'postgresql', 'pyenv', 'redis', 'zsh']
    state: latest

- name: Install Casks
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - aws-vault
    - aerial
    - atom
    - bartender
    - brave-browser
    - caprine
    - dropbox
    - firefox
    - fork
    - google-backup-and-sync
    - google-chrome
    - iterm2
    - java
    - pgadmin4
    - pycharm
    - sequel-pro
    - slack
    - spectacle
    - spotify
    - zoomus
